SELECT * FROM pelicula
ORDER BY pelicula.duracion DESC;
----------------------------------------------

SELECT * FROM actor
WHERE actor.nombre LIKE 'S%_';
-----------------------------------------------

SELECT * FROM pelicula,actor
ORDER BY actor.nombre;
-----------------------------------------------
SELECT * FROM pelicula
WHERE estudio = 3

UNION

SELECT * FROM pelicula
WHERE estudio = 5
--------------------------------------------------

SELECT COUNT(codigo_pelicula), productor.nombre FROM productor,producir
GROUP BY (productor.nombre)
ORDER BY productor.nombre;
---------------------------------------------------
